name: Make description PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Convert to PDF
      run: make latex
      
    - uses: actions/upload-artifact@v2
      with:
        name: synthetic-asset-contract
        path: synthetic-asset-contract.pdf
      
